name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag raspberryhelloworld:latest
    - uses: actions/checkout@v2
    - name: Tag the Docker image
      run: docker tag raspberryhelloworld rcwowbagger/raspberryhelloworld
    - uses: actions/checkout@v2
    - name: Login to Docker
      run: docker login -u ${{ secrets.docker_username }} -p ${{ secrets.docker_key }}
    - uses: actions/checkout@v2
    - name: Push the Docker image
      run: docker push rcwowbagger/raspberryhelloworld
