name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag raspberryhelloworld:$(date +%s)
    - uses: actions/checkout@v2
    - name: Tag the Docker image
      run: docker tag raspberryhelloworld rcwowbagger/raspberryhelloworld
    - uses: actions/checkout@v2
    - name: Push the Docker image
      run: docker push rcwowbagger/raspberryhelloworld
